name = "PolyChaosODE"
uuid = "af2d7fda-267f-4d47-b1ea-decec08f76a9"
authors = ["Diogo Netto <diogonetto.dcn@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
